// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // Migrations need a direct (non-pooled) connection — pgbouncer's transaction-mode
    // pooling (used by DATABASE_URL in production) doesn't support the advisory lock
    // Prisma Migrate uses to coordinate, which makes `migrate deploy` hang. Locally
    // there's no pooler in front of Postgres, so DATABASE_URL is already a direct
    // connection and this just falls back to it.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
